### ISSUE TITLE
Does anyone convert microdata to JSON?

### ISSUE THREAD

**Issue by chaals** [w3c/microdata#15]
If not, should we remove that bit?

**Comment by danbri** [comment]
At Google we parse Microdata and JSON-LD into a common (reasonably RDFish) abstraction. The flow is much more from such concrete formats into triples/graphs than back out into re-serialized JSON(-LD), but this is the closest we get to microdata/JSON mapping afaik. I don't believe we (Google 'we') do anything with the Microdata spec's JSON mapping.

**Comment by chaals** [comment]
If we remove it, we may as well also deprecate the application/microdata+json stuff - it's main use case was alleged to be drag and drop, which we already recognised as an experiment that didn't get traction.

**Comment by danbri** [comment]
see also application/microdata+json registration, https://www.ietf.org/mail-archive/web/ietf-types/current/msg01714.html

Presumably we'd need to tidy things up there, or leave a legacy section for that to reference.

**Comment by chaals** [comment]
Hmm. Maybe the sensible path is to leave it there.

The security considerations section of the equivalent for JSON-LD looks like we should copy^Wimprove the quality of our spec by consideration of the issues it describes.

**Comment by chaals** [comment]
See also [JSON](https://tools.ietf.org/html/rfc4627) which is what we currently claim has the same security considerations

**Comment by chaals** [comment]
OK, let's leave this here. It doesn't hurt anyone.
