### ISSUE TITLE
Microdata should include RDF processing model

### ISSUE THREAD

**Issue by gkellogg** [w3c/microdata#3]
The primary use of Microdata on the web is to contain schema.org-based metadata. From the [recent common crawl](http://webdatacommons.org/structureddata/2016-10/stats/stats.html) 2.5/3 million pages include Microdata. All of this data has an RDF interpretation, which is in fact critical to extracting information from the pages.

The microdata spec should integrate the work from the [Microdata to RDF Note](https://www.w3.org/TR/microdata-rdf/).

**Comment by chaals** [comment]
I'm more tempted to make this spec **informatively** describe conversion to RDFa/JSON-LD as per #5, recognising that microdata is a pretty loose format, and provide an informative link to the conversion note for those who want more details…

**Comment by chaals** [comment]
I propose to close this with an explanation that when microdata is parsed to RDF people generally the microdata-to-rdf note, and whatever we resolve for #29, #34 and #41. @danbri?

**Comment by gkellogg** [comment]
See https://github.com/w3c/microdata-rdf/pull/28 for a proposed update to Microdata to RDF to align with this version of Microdata; it could also be considered as a basis for an RDF processing section directly within the spec.

**Comment by danbri** [comment]
closing per @chaals suggested approach
