### ISSUE TITLE
incomplete sentence "User agents are"

### ISSUE THREAD

**Issue by Nick-Levinson** [w3c/microdata#77]
A sentence fragment says "User agents are " (including the trailing space) and nothing more. Either it needs more or it should be deleted. It's in the W3C Working Draft of June 26, 2017, section 5.2, Note (green box), at the end.

**Comment by chaals** [comment]
Yes. We removed it from the editor's draft, but a Gremlin seems to have put it back into some stuff. Following up now - I think it's a tooling issue :(

Thank you for noting.

**Comment by chaals** [comment]
Fixed in the latest [Public Working Draft](https://www.w3.org/TR/2017/WD-microdata-20171010/) and [editors' draft](https://w3c.github.io/microdata/).

Thanks again.
